[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
obridge = "FAqaHQHgBFFX8fJB6fQUqNdc8zABV5pGVRdCt7fLLYVo"
obridge_swap = "DnSgZFH2hMgZ7bXmJUdcL8bgB1MgDpVtddNhwzZACTKQ"

[programs.devnet]
obridge = "FAqaHQHgBFFX8fJB6fQUqNdc8zABV5pGVRdCt7fLLYVo"
obridge_swap = "DnSgZFH2hMgZ7bXmJUdcL8bgB1MgDpVtddNhwzZACTKQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
